#!/usr/bin/env ruby

require "mk_coord"

EPS = 23.43929 * MkCoord::Const::PI / 180.0    # 黄道傾斜角(単位: rad)
# 元の赤道直交座標
POS = [
   0.99443659220700997281,
  -0.03816291768957833647,
  -0.01655177670960058384
]  # <= ある日の地球重心から見た太陽重心の位置(単位: AU)

puts "RECT_EQ = #{POS}"
rect_ec = MkCoord.rect_eq2ec(POS, EPS)
puts "RECT_EC = #{rect_ec}"
rect_eq = MkCoord.rect_ec2eq(rect_ec, EPS)
puts "RECT_EQ = #{rect_eq}"
*pol_eq, r = MkCoord.rect2pol(rect_eq)
puts " POL_EQ = #{pol_eq[0, 2]} (R = #{r})"
pol_ec = MkCoord.pol_eq2ec(pol_eq[0, 2], EPS)
puts " POL_EC = #{pol_ec[0, 2]}"
pol_eq = MkCoord.pol_ec2eq(pol_ec, EPS)
puts " POL_EQ = #{pol_eq[0, 2]}"
rect_eq = MkCoord.pol2rect(pol_eq[0, 2], r)
puts "RECT_EQ = #{rect_eq}"

